fullnameOverride: mysql

image:
  registry: docker.io
  repository: bitnami/mysql
  tag: "8.0.36-debian-12-r0"
  pullPolicy: IfNotPresent

architecture: standalone

auth:
  rootPassword: "ChangeMe_Root_123!"
  createDatabase: true
  database: app
  username: app_user
  password: "ChangeMe_App_123!"

primary:
  service:
    type: ClusterIP
    ports:
      mysql: 3306

  persistence:
    enabled: true
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    size: 20Gi

  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 2Gi

  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6

  readinessProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6

  startupProbe:
    enabled: true
    initialDelaySeconds: 15
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 30

secondary:
  replicaCount: 0

metrics:
  enabled: false

networkPolicy:
  enabled: false
