fullnameOverride: mysql

nameOverride: ""

image:
  registry: docker.io
  repository: mysql
  tag: "8.4.0"
  pullPolicy: IfNotPresent
  pullSecrets: []

auth:
  rootPassword: "root"
  createDatabase: true
  database: xdev
  username: xdev
  password: "1234"

service:
  type: ClusterIP
  port: 3306

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 20Gi

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 2Gi

probes:
  liveness:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
  readiness:
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
  startup:
    initialDelaySeconds: 15
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 30

initdbScripts: {}

extraEnv: []
podAnnotations: {}
nodeSelector: {}
tolerations: []
affinity: {}
