# values-apollo-portal.yaml
portaldb:
  host: mysql.xdev.svc.cluster.local
  port: 3306
  dbName: ApolloPortalDB
  userName: apollo
  password: apollo
  connectionStringProperties: "useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai"
  service:
    enabled: false

replicaCount: 1   # 内网测试 1 够；生产建议 2

image:
  repository: apolloconfig/apollo-portal
  tag: "2.5.0"    # 锁版本

config:
  profiles: "github,auth"
  envs: "dev"  # 单集群单环境也要给一个名字
  metaServers:
    dev: "http://apollo-service-apollo-configservice.xdev.svc.cluster.local:8080"

service:
  type: ClusterIP
  port: 8070
  targetPort: 8070

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 2Gi
