# values-apollo-service.yaml
configdb:
  host: mysql.xdev.svc.cluster.local
  port: 3306
  dbName: ApolloConfigDB
  userName: apollo
  password: apollo
  connectionStringProperties: characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
  service:
    enabled: false

configService:
  replicaCount: 2        # 内网测试 2 够用；生产建议 3+
  image:
    repository: apolloconfig/apollo-configservice
    tag: "2.5.0"         # 建议锁版本（示例用 Apollo 2.5.0）
  config:
    profiles: "github,kubernetes"
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 2Gi

adminService:
  replicaCount: 1        # 内网测试 1 够用；生产建议 2
  image:
    repository: apolloconfig/apollo-adminservice
    tag: "2.5.0"
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 2Gi
